name: QA Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install robotframework robotframework-seleniumlibrary robotframework-requests webdriver-manager

    - name: Setup Chrome & Driver
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable

    - name: Check Chrome Version
      run: google-chrome --version

    - name: Run Robot Web Tests
      run: |
        robot -d relatorio tests/web

    - name: Upload Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: robot-results
        path: relatorio/
